heat_template_version: 2015-10-15

description: |
  #### Creates:
  #### - Ubuntu 16 LTS OnMetal server, then performs a
  ####   dist-upgrade to Ubuntu 18 LTS
  #### Author: Brian King
  #### License: Apache
  #### version: 0.0.1a
  #### last modified: 2020-03-11


parameter_groups:

- label: onMetal Settings
  parameters:
    - onMetalName
    - onMetalFlavor
    - onMetalKey

parameters:

  onMetalName:
    type: string
    label: 'Name of OnMetal server'
    default: 'OnMetal-00'
    constraints:
      - allowed_pattern: '^[\w-]+$'
        description: "Server name may only have alphanumeric characters, underscores, and dashes"

  onMetalFlavor:
    type: string
    default: OnMetal General Purpose v2 Small
    label: OnMetal Flavor ID
    description: Must be a valid Rackspace Cloud Flavor
    constraints:
    - allowed_values:
      - OnMetal General Purpose v2 Large
      - OnMetal General Purpose v2 Medium
      - OnMetal General Purpose v2 Small
      - OnMetal IO v1
      - OnMetal I/O v2
      - OnMetal Memory v1
      - OnMetal Compute v1
      description: must be a valid Rackspace Cloud OnMetal flavor.


  onMetalKey:
    type: string
    description: Keypair
    label: SSH Keypair
    constraints:
      - custom_constraint: nova.keypair

resources:

  onMetalCloudConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
              #!/usr/bin/env bash

              #dist-upgrade.sh, upgrades Ubuntu 16 LTS server to latest
              #LTS release

              export DEBIAN_FRONTEND=noninteractive
              do-release-upgrade -f DistUpgradeViewNonInteractive
              rm /etc/apt/sources.list.d/*.save
              reboot

  onMetalInstance:
    type: OS::Nova::Server
    properties:
      name: { get_param: onMetalName }
      image: "OnMetal - Ubuntu 16.04 LTS (Xenial Xerus) (Vendor)"
      key_name: { get_param: onMetalKey }
      flavor: { get_param: onMetalFlavor }
      metadata:
        created_by: cloud_orch_template
      config_drive: True
      user_data: { get_resource: onMetalCloudConfig }
      networks:
        - network: '00000000-0000-0000-0000-000000000000'
        - network: '11111111-1111-1111-1111-111111111111'
